# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3f2faac1879175a78f8acee58dea0bf0e318e761b27c86d07846c024c3d2c1284fc0a01ad163c280a4fce0dab597ab24f30a5d026e5eecf104061a678e13702

test:
  secret_key_base: 705addf16a45d60e7a3a3b84f807a7e0622e0f0215c8d18eef686bdc9da23c2acd6321a17715c4a5c246d289fc5b8c8c4a1bf5d407035e0dbb85a3662a3385dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
